background = #14090e
foreground = #d4b8be
cursor-color = #ebd4d9
selection-background = #3d1520
selection-foreground = #ebd4d9

palette = 0=#14090e
palette = 1=#ff3b56
palette = 2=#e6495f
palette = 3=#f5b867
palette = 4=#c7384c
palette = 5=#ba3247
palette = 6=#e07085
palette = 7=#d4b8be
palette = 8=#5c2430
palette = 9=#ff5c72
palette = 10=#f55b70
palette = 11=#ffd08a
palette = 12=#e0485d
palette = 13=#d64057
palette = 14=#f78aa0
palette = 15=#ebd4d9
