foreground #d4b8be
background #14090e
selection_foreground #ebd4d9
selection_background #3d1520

cursor #ebd4d9
cursor_text_color #14090e

active_border_color #ff3b56
active_tab_background #ff3b56

color0 #14090e
color1 #ff3b56
color2 #e6495f
color3 #f5b867
color4 #c7384c
color5 #ba3247
color6 #e07085
color7 #d4b8be
color8 #5c2430
color9 #ff5c72
color10 #f55b70
color11 #ffd08a
color12 #e0485d
color13 #d64057
color14 #f78aa0
color15 #ebd4d9
